package sensor

import (
	"math/rand"
	"time"

	"github.com/mcprice30/wmn/data"
)

// OxygenSensorInterval indicates how often data is generated by the oxgyen
// level sensor before being sent to the hub.
const OxygenSensorInterval = "2000ms"

// OxygenSensor represents the oxygen level sensor in the first responder's air
// pack. It impements sensor.SensorStream, allowing for the data it generates
// to be sent to the sensor hub.
type OxygenSensor struct {
	// interval indicates how often data is generated.
	interval time.Duration
	// id is the id of the upcoming data segment, used in sequencing data.
	id byte

	lastOx float64
}

// CreateOxygenSensor will create a new instance of OxygenSensor.
func CreateOxygenSensor() *OxygenSensor {
	return &OxygenSensor{
		interval: intervalFromString(OxygenSensorInterval),
		lastOx:   100.0,
	}
}

// Interval indicates how regularly data is generated by the sensor.
// It implements SensorStream.
func (s *OxygenSensor) Interval() time.Duration {
	return s.interval
}

// GetDaata will generate a new data point from the sensor.
// It implements SensorStream.
func (s *OxygenSensor) GetData() data.SensorData {
	pct := s.lastOx - rand.Float64()*0.01
	s.lastOx = pct
	defer s.incrementId()
	return data.CreateOxygenData(s.id, pct)
}

// incrementId will increase the packet id, used in sequencing data.
func (s *OxygenSensor) incrementId() {
	s.id++
}
