// Package sensor contains implementations of the various sensors that send
// data to the Sensor Hub.
//
// Currently, this consists of:
//
// GasSensor:		Monitors the levels of toxic gas. Data is sent as data.GasData
// packets, at an interval of 250ms.
//
// HeartRateSensor: Monitors the wearer's heart rate. Data is sent as
// data.HeartRateData packets, at an interval of 1000ms.
//
// LocationSensor: Monitors the current location of the wearer. Data is sent
// as data.LocationData packets, at an interval of 500ms.
//
// OxygenSensor: Monitors the oxygen level of the wearer's air-pack. Data is
// sent as data.OxygenData packets, at an interval of 2000ms.
package sensor

import (
	"math/rand"
	"time"

	"github.com/mcprice30/wmn/data"
)

// GasSensorInterval indicates how often data is generated by the toxic gas
// sensor, before being sent to the sensor hub.
const GasSensorInterval = "250ms"

// GasSensor represents the toxic gas sensor attached to the first responder.
// It implements sensor.SensorStream, allowing for the data it generates to be
// sent to the sensor hub.
type GasSensor struct {
	// interval indicates how often data is generated.
	interval time.Duration
	// id is the id of the upcoming data segment, used in sequencing data.
	id byte
}

// CreateGasSensor will create a new instance of GasSensor.
func CreateGasSensor() *GasSensor {
	return &GasSensor{
		interval: intervalFromString(GasSensorInterval),
	}
}

// Interval indicates how regularly data is generated by the sensor.
// It implements SensorStream.
func (s *GasSensor) Interval() time.Duration {
	return s.interval
}

// GetData will generate a new data point from the sensor.
// It implements SensorStream.
func (s *GasSensor) GetData() data.SensorData {
	pct := rand.Float64() * 15.0
	defer s.incrementId()
	return data.CreateGasData(s.id, pct)
}

// incrementId will increase the packet id, used in sequencing data.
func (s *GasSensor) incrementId() {
	s.id++
}
