// package Sensor contains implementations of the various sensors that send
// data to the Sensor Hub.
//
// Currently, this consists of:
//
// GasSensor:		Monitors the levels of toxic gas. Data is sent as data.GasData
// packets, at an interval of 250ms.
//
// HeartRateSensor: Monitors the wearer's heart rate. Data is sent as
// data.HeartRateData packets, at an interval of 1000ms.
//
// LocationSensor: Monitors the current location of the wearer. Data is sent
// as data.LocationData packets, at an interval of 500ms.
//
// OxygenSensor: Monitors the oxygen level of the wearer's air-pack. Data is
// sent as data.OxygenData packets, at an interval of 2000ms.
package sensor

import (
	"math/rand"
	"time"

	"github.com/mcprice30/wmn/data"
)

// OxygenSensorInterval indicates how often data is generated by the oxgyen
// level sensor before being sent to the hub.
const OxygenSensorInterval = "2000ms"

// OxygenSensor represents the oxygen level sensor in the first responder's air
// pack. It impements sensor.SensorStream, allowing for the data it generates
// to be sent to the sensor hub.
type OxygenSensor struct {
	// interval indicates how often data is generated.
	interval time.Duration
	// id is the id of the upcoming data segment, used in sequencing data.
	id byte
}

// CreateOxygenSensor will create a new instance of OxygenSensor.
func CreateOxygenSensor() *OxygenSensor {
	return &OxygenSensor{
		interval: intervalFromString(OxygenSensorInterval),
	}
}

// Interval indicates how regularly data is generated by the sensor.
// It implements SensorStream.
func (s *OxygenSensor) Interval() time.Duration {
	return s.interval
}

// GetDaata will generate a new data point from the sensor.
// It implements SensorStream.
func (s *OxygenSensor) GetData() data.SensorData {
	pct := rand.Float64() * 100.0
	defer s.incrementId()
	return data.CreateOxygenData(s.id, pct)
}

// incrementId will increase the packet id, used in sequencing data.
func (s *OxygenSensor) incrementId() {
	s.id++
}
